### ISSUE TITLE
copy to sent folder after sending not work in thunderbird

### ISSUE THREAD

**Issue by Sebijk** [b1gMail/b1gMailServer#14]
If an email is sent, it will not stored in sent and thunderbird give an error, that the email cannot saved.

The logs:

[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] Connected
[Fri Mar  1 19:21:22 2024] - IMAP - 8 - #3 - [0.0.0.0] Data: 38 capability
[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] CAPABILITY
[Fri Mar  1 19:21:22 2024] - IMAP - 8 - #3 - [0.0.0.0] Data: 39 authenticate PLAIN
[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] AUTHENTICATE
[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] Logged in as xx@domain.tld
[Fri Mar  1 19:21:22 2024] - IMAP - 8 - #3 - [HELPER] Fetched [35] folders of user [1]
[Fri Mar  1 19:21:22 2024] - IMAP - 8 - #3 - [0.0.0.0] Data: 40 capability
[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] CAPABILITY
[Fri Mar  1 19:21:22 2024] - IMAP - 8 - #3 - [0.0.0.0] Data: 41 append "Sent" (\Seen) {4263}
[Fri Mar  1 19:21:22 2024] - IMAP - 1 - #3 - [0.0.0.0] APPEND
[Fri Mar  1 19:21:42 2024] - IMAP - 1 - #3 - [0.0.0.0] Disconnected

This happens also, when Thunderbird try to store an email to Drafts Folder.

**Comment by pschlan** [comment]
Thanks for reporting, this should be fixed now.
