### ISSUE TITLE
IMAP: COPY command without effect

### ISSUE THREAD

**Issue by Loadbox2k3** [b1gMail/b1gMailServer#6]
Mails that are deleted with a client do not end up in the trash, but disappear and end up nowhere

**Comment by pschlan** [comment]
The IMAP protocol has no notion of a Trash folder. It's up to the client to move mails instead of deleting them.

**Comment by Loadbox2k3** [comment]
so i have tested it! its exact the same situation! 
at this point : 
when i delete mails do not end up in the trash
when i move mails to a folder do not end up in the folder

in both cases the emails are gone and cannot be found
