### ISSUE TITLE
No Log in Admin Area

### ISSUE THREAD

**Issue by Loadbox2k3** [b1gMail/b1gMailServer#8]
after the update the Logs in Admin Area are broken

**Comment by pschlan** [comment]
Which update?
With current main branch, can't reproduce this.

Can you share your /opt/b1gmailserver/b1gmailserver.cfg?

**Comment by Loadbox2k3** [comment]
# Für Fail2Ban bitte den FileLog Aktivieren
logfile         = /var/log/b1gmailserver/b1gmailserver.log

this was the failure! after delete this ,logs are in ACP visible!

where is the default log path for b1gmailserver?
